//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckSLATStatusOfMachine.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CheckSLATStatusOfMachine.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Exception---- Details {0} {1}.
        /// </summary>
        internal static string GeneralExceptionStr {
            get {
                return ResourceManager.GetString("GeneralExceptionStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a SLAT capable machine, but hardware virualization is disabled at BIOS level, so please enable it..
        /// </summary>
        internal static string HWVirtualizationDisabled {
            get {
                return ResourceManager.GetString("HWVirtualizationDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your machine does not have hardware virtualization capability. So, your machine is not SLAT capable..
        /// </summary>
        internal static string NotSlatEnabled {
            get {
                return ResourceManager.GetString("NotSlatEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should be checked only on Windows 8 or later OS..
        /// </summary>
        internal static string NotWin8 {
            get {
                return ResourceManager.GetString("NotWin8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SecurityException---- Details {0} {1}.
        /// </summary>
        internal static string SecurityExceptionStr {
            get {
                return ResourceManager.GetString("SecurityExceptionStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a SLAT capable machine..
        /// </summary>
        internal static string SlatEnabled {
            get {
                return ResourceManager.GetString("SlatEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnauthorizedAccessException---- Details {0} {1}.
        /// </summary>
        internal static string UnauthorizedAccessExceptionStr {
            get {
                return ResourceManager.GetString("UnauthorizedAccessExceptionStr", resourceCulture);
            }
        }
    }
}
